name = "tcdb-edge"
main = "dist/index.js"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
ORIGIN_URL = "https://api.tcdb.uk"

# Secrets (set via: wrangler secret put EDGE_HMAC_SECRET)
# EDGE_HMAC_SECRET = "..." (set via CLI, not in this file)

# Durable Objects for rate limiting
[[durable_objects.bindings]]
name = "RATE_DO"
class_name = "RateLimiter"
script_name = "tcdb-edge"

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]

# Routes - map API paths to this worker
# Uncomment when deploying to production
# [[routes]]
# pattern = "tcdb.uk/api/*"
# zone_name = "tcdb.uk"

