services:
  - type: web
    name: tcdb-core-homepage
    env: static
    buildCommand: echo "No build needed for static site"
    staticPublishPath: ./docs
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

