name = "tcdb-auth"
main = "auth-worker.js"
compatibility_date = "2024-01-01"

# KV Namespaces for data storage
[[kv_namespaces]]
binding = "USERS"
id = "3566a577752c4e94b1ff84a94c5e567c"

[[kv_namespaces]]
binding = "SESSIONS"
id = "e8a0c89d87fa452b92bec9bad0b1846d"

[[kv_namespaces]]
binding = "AUTH_TOKENS"
id = "07f93ea2cc364645be74036543469095"

[[kv_namespaces]]
binding = "API_KEYS"
id = "ff63a5baf8c84b6a8e5e851a574d9e26"

