[package]
name = "topological_streaming_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32"
rayon = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "topological_streaming_engine"
crate-type = ["cdylib", "rlib"]
